# This Makefile is generated by omake: https://github.com/ouonline/omake.git

AR := ar
CXX := g++

ifeq ($(debug), y)
	CXXFLAGS := -g
else
	CXXFLAGS := -O2 -DNDEBUG
endif
CXXFLAGS := $(CXXFLAGS) -Wall -Werror -Wextra -fPIC

TARGET := omake

.PHONY: all clean

all: $(TARGET)

.PHONY: __omake_dep__2 __omake_dep__1

__omake_dep__2:
	$(MAKE) debug=$(debug) libtext_utils.a -C ../text-utils

__omake_dep__1:
	$(MAKE) debug=$(debug) libluacpp.a -C ../lua-cpp

omake_OBJS := project.cpp.omake.o target.cpp.omake.o misc.cpp.omake.o main.cpp.omake.o

omake_INCLUDE := -I.. -I../../../lua

omake_LIBS := ../lua-cpp/libluacpp.a ../text-utils/libtext_utils.a ../../../lua/src/liblua.a -ldl -lm

project.cpp.omake.o: project.cpp
	$(CXX) $(CXXFLAGS) $(omake_INCLUDE) -c $< -o $@

target.cpp.omake.o: target.cpp
	$(CXX) $(CXXFLAGS) $(omake_INCLUDE) -c $< -o $@

misc.cpp.omake.o: misc.cpp
	$(CXX) $(CXXFLAGS) $(omake_INCLUDE) -c $< -o $@

main.cpp.omake.o: main.cpp
	$(CXX) $(CXXFLAGS) $(omake_INCLUDE) -c $< -o $@

omake: $(omake_OBJS) | __omake_dep__1 __omake_dep__2
	$(CXX) $(CXXFLAGS) -o $@ $^ $(omake_LIBS)

clean:
	rm -f $(TARGET) $(omake_OBJS)
